In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)

In [2]:
PROJECT_DIR = Path.cwd().parent

DATA = PROJECT_DIR / "processed" / "master1_dataset.csv"

df = pd.read_csv(DATA)

print(df.shape)

df.head()

(23424, 44)

,Week,Measurement_Site,Latitude,Longitude,Source_File,Vehicle_Category,Time,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Fahrtrichtung Nord-Ost.1,Fahrtrichtung Süd-West.1,von Rechts nach Unten,von Rechts nach Oben,Von Links nach Oben,Von Links nach Unten,Von Oben nach Unten,Fahrtrichtung Süd,Fahrtrichtung Nord,Fahrtrichtung West,Fahrtrichtung Ost,Leicht-rechts in Links,Rechts in Oben,Geradeaus in Links,Rechts in Oben.1,Falschfahrer,Falschfahrer.1,Falschfahrer.2,Geradeaus in Unten,Geradeaus in Oben,Fahrtrichtung Nord.1,Fahrtrichtung Süd.1,von Rechts Links nach Unten,von Links Geradeaus in Rechts,von Oben Links in Rechts,von Oben Geradeaus in Unten,von Unten Geradeaus in Oben,nach Unten,Total_Traffic
0,DZwEI 08.10-13.10,Glauburgstraße,50.127065,8.689309,2024-10-08_to_2024-10-13_UI_202403B0923.xlsx,Bus,00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,DZwEI 08.10-13.10,Glauburgstraße,50.127065,8.689309,2024-10-08_to_2024-10-13_UI_202403B0923.xlsx,Bus,00:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,DZwEI 08.10-13.10,Glauburgstraße,50.127065,8.689309,2024-10-08_to_2024-10-13_UI_202403B0923.xlsx,Bus,00:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,DZwEI 08.10-13.10,Glauburgstraße,50.127065,8.689309,2024-10-08_to_2024-10-13_UI_202403B0923.xlsx,Bus,00:45:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0
4,DZwEI 08.10-13.10,Glauburgstraße,50.127065,8.689309,2024-10-08_to_2024-10-13_UI_202403B0923.xlsx,Bus,01:00:00,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0

In [3]:
print("="*60)
print("DATASET INFORMATION")
print("="*60)

df.info()

============================================================
DATASET INFORMATION
============================================================
<class 'pandas.DataFrame'>
RangeIndex: 23424 entries, 0 to 23423
Data columns (total 44 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Week                           23424 non-null  str
 1   Measurement_Site               23424 non-null  str
 2   Latitude                       8448 non-null   float64
 3   Longitude                      8448 non-null   float64
 4   Source_File                    23424 non-null  str
 5   Vehicle_Category               23424 non-null  str
 6   Time                           23424 non-null  str
 7   von Unten nach Oben            23424 non-null  float64
 8   von Links nach Oben            23424 non-null  float64
 9   von Links nach Unten           23424 non-null  float64
 10  von Oben nach Unten            23424 non-null  float64
 11  Fahrtrichtung Süd-West         23424 non-null  float64
 12  Fahrtrichtung Nord-Ost         23424 non-null  float64
 13  Fahrtrichtung Nord-West        23424 non-null  float64
 14  Fahrtrichtung Süd-Ost          23424 non-null  float64
 15  Fahrtrichtung Nord-Ost.1       23424 non-null  float64
 16  Fahrtrichtung Süd-West.1       23424 non-null  float64
 17  von Rechts nach Unten          23424 non-null  float64
 18  von Rechts nach Oben           23424 non-null  float64
 19  Von Links nach Oben            23424 non-null  float64
 20  Von Links nach Unten           23424 non-null  float64
 21  Von Oben nach Unten            23424 non-null  float64
 22  Fahrtrichtung Süd              23424 non-null  float64
 23  Fahrtrichtung Nord             23424 non-null  float64
 24  Fahrtrichtung West             23424 non-null  float64
 25  Fahrtrichtung Ost              23424 non-null  float64
 26  Leicht-rechts in Links         23424 non-null  float64
 27  Rechts in Oben                 23424 non-null  float64
 28  Geradeaus in Links             23424 non-null  float64
 29  Rechts in Oben.1               23424 non-null  float64
 30  Falschfahrer                   23424 non-null  float64
 31  Falschfahrer.1                 23424 non-null  float64
 32  Falschfahrer.2                 23424 non-null  float64
 33  Geradeaus in Unten             23424 non-null  float64
 34  Geradeaus in Oben              23424 non-null  float64
 35  Fahrtrichtung Nord.1           23424 non-null  float64
 36  Fahrtrichtung Süd.1            23424 non-null  float64
 37  von Rechts Links nach Unten    23424 non-null  float64
 38  von Links Geradeaus in Rechts  23424 non-null  float64
 39  von Oben Links in Rechts       23424 non-null  float64
 40  von Oben Geradeaus in Unten    23424 non-null  float64
 41  von Unten Geradeaus in Oben    23424 non-null  float64
 42  nach Unten                     23424 non-null  float64
 43  Total_Traffic                  23424 non-null  float64
dtypes: float64(39), str(5)
memory usage: 10.0 MB

In [4]:
missing = pd.DataFrame({

    "Missing Values": df.isnull().sum(),

    "Percentage (%)": round(df.isnull().mean()*100,2)

})

missing.sort_values(
    "Missing Values",
    ascending=False
)

                               Missing Values  Percentage (%)
Longitude                               14976           63.93
Latitude                                14976           63.93
Measurement_Site                            0            0.00
Week                                        0            0.00
Source_File                                 0            0.00
Vehicle_Category                            0            0.00
Time                                        0            0.00
von Unten nach Oben                         0            0.00
von Links nach Oben                         0            0.00
von Links nach Unten                        0            0.00
von Oben nach Unten                         0            0.00
Fahrtrichtung Süd-West                      0            0.00
Fahrtrichtung Nord-Ost                      0            0.00
Fahrtrichtung Nord-West                     0            0.00
Fahrtrichtung Süd-Ost                       0            0.00
Fahrtrichtung Nord-Ost.1                    0            0.00
Fahrtrichtung Süd-West.1                    0            0.00
von Rechts nach Unten                       0            0.00
von Rechts nach Oben                        0            0.00
Von Links nach Oben                         0            0.00
Von Links nach Unten                        0            0.00
Von Oben nach Unten                         0            0.00
Fahrtrichtung Süd                           0            0.00
Fahrtrichtung Nord                          0            0.00
Fahrtrichtung West                          0            0.00
Fahrtrichtung Ost                           0            0.00
Leicht-rechts in Links                      0            0.00
Rechts in Oben                              0            0.00
Geradeaus in Links                          0            0.00
Rechts in Oben.1                            0            0.00
Falschfahrer                                0            0.00
Falschfahrer.1                              0            0.00
Falschfahrer.2                              0            0.00
Geradeaus in Unten                          0            0.00
Geradeaus in Oben                           0            0.00
Fahrtrichtung Nord.1                        0            0.00
Fahrtrichtung Süd.1                         0            0.00
von Rechts Links nach Unten                 0            0.00
von Links Geradeaus in Rechts               0            0.00
von Oben Links in Rechts                    0            0.00
von Oben Geradeaus in Unten                 0            0.00
von Unten Geradeaus in Oben                 0            0.00
nach Unten                                  0            0.00
Total_Traffic                               0            0.00

In [6]:
#remove duplicates
print("Before :", len(df))

df = df.drop_duplicates()

print("After :", len(df))

Before : 23424
After : 23424

In [7]:
#missing traffic values
metadata_cols = [

    "Week",

    "Measurement_Site",

    "Latitude",

    "Longitude",

    "Source_File",

    "Vehicle_Category",

    "Time",

    "Total_Traffic"

]

traffic_cols = [

    c

    for c in df.columns

    if c not in metadata_cols

]

df[traffic_cols] = df[traffic_cols].fillna(0)

In [8]:
for col in traffic_cols:

    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

In [9]:
df["Total_Traffic"] = df[traffic_cols].sum(axis=1)

In [10]:
df["Time"] = pd.to_datetime(
    df["Time"],
    format="%H:%M:%S",
    errors="coerce"
)

In [11]:
df["Hour"] = df["Time"].dt.hour

df["Minute"] = df["Time"].dt.minute

In [12]:
def peak_period(hour):

    if 6 <= hour < 10:

        return "Morning Peak"

    elif 10 <= hour < 15:

        return "Midday"

    elif 15 <= hour < 19:

        return "Evening Peak"

    else:

        return "Off Peak"


df["Peak_Period"] = df["Hour"].apply(peak_period)

In [13]:
df["Time_Interval"] = (

    df["Hour"].astype(str).str.zfill(2)

    + ":"

    + df["Minute"].astype(str).str.zfill(2)

)

In [14]:
df.dtypes

Week                                        str
Measurement_Site                            str
Latitude                                float64
Longitude                               float64
Source_File                                 str
Vehicle_Category                            str
Time                             datetime64[us]
von Unten nach Oben                     float64
von Links nach Oben                     float64
von Links nach Unten                    float64
von Oben nach Unten                     float64
Fahrtrichtung Süd-West                  float64
Fahrtrichtung Nord-Ost                  float64
Fahrtrichtung Nord-West                 float64
Fahrtrichtung Süd-Ost                   float64
Fahrtrichtung Nord-Ost.1                float64
Fahrtrichtung Süd-West.1                float64
von Rechts nach Unten                   float64
von Rechts nach Oben                    float64
Von Links nach Oben                     float64
Von Links nach Unten                    float64
Von Oben nach Unten                     float64
Fahrtrichtung Süd                       float64
Fahrtrichtung Nord                      float64
Fahrtrichtung West                      float64
Fahrtrichtung Ost                       float64
Leicht-rechts in Links                  float64
Rechts in Oben                          float64
Geradeaus in Links                      float64
Rechts in Oben.1                        float64
Falschfahrer                            float64
Falschfahrer.1                          float64
Falschfahrer.2                          float64
Geradeaus in Unten                      float64
Geradeaus in Oben                       float64
Fahrtrichtung Nord.1                    float64
Fahrtrichtung Süd.1                     float64
von Rechts Links nach Unten             float64
von Links Geradeaus in Rechts           float64
von Oben Links in Rechts                float64
von Oben Geradeaus in Unten             float64
von Unten Geradeaus in Oben             float64
nach Unten                              float64
Total_Traffic                           float64
Hour                                      int32
Minute                                    int32
Peak_Period                                 str
Time_Interval                               str
dtype: object

In [15]:
df.isnull().sum().sort_values(
    ascending=False
)

Longitude                        14976
Latitude                         14976
Measurement_Site                     0
Week                                 0
Source_File                          0
Vehicle_Category                     0
Time                                 0
von Unten nach Oben                  0
von Links nach Oben                  0
von Links nach Unten                 0
von Oben nach Unten                  0
Fahrtrichtung Süd-West               0
Fahrtrichtung Nord-Ost               0
Fahrtrichtung Nord-West              0
Fahrtrichtung Süd-Ost                0
Fahrtrichtung Nord-Ost.1             0
Fahrtrichtung Süd-West.1             0
von Rechts nach Unten                0
von Rechts nach Oben                 0
Von Links nach Oben                  0
Von Links nach Unten                 0
Von Oben nach Unten                  0
Fahrtrichtung Süd                    0
Fahrtrichtung Nord                   0
Fahrtrichtung West                   0
Fahrtrichtung Ost                    0
Leicht-rechts in Links               0
Rechts in Oben                       0
Geradeaus in Links                   0
Rechts in Oben.1                     0
Falschfahrer                         0
Falschfahrer.1                       0
Falschfahrer.2                       0
Geradeaus in Unten                   0
Geradeaus in Oben                    0
Fahrtrichtung Nord.1                 0
Fahrtrichtung Süd.1                  0
von Rechts Links nach Unten          0
von Links Geradeaus in Rechts        0
von Oben Links in Rechts             0
von Oben Geradeaus in Unten          0
von Unten Geradeaus in Oben          0
nach Unten                           0
Total_Traffic                        0
Hour                                 0
Minute                               0
Peak_Period                          0
Time_Interval                        0
dtype: int64

In [16]:
print("="*60)

print("Rows :", len(df))

print("Columns :", len(df.columns))

print("Vehicle Categories :", df["Vehicle_Category"].nunique())

print("Measurement Sites :", df["Measurement_Site"].nunique())

print("Peak Periods")

print(df["Peak_Period"].value_counts())

print("="*60)

============================================================
Rows : 23424
Columns : 48
Vehicle Categories : 11
Measurement Sites : 11
Peak Periods
Peak_Period
Off Peak        10736
Midday           4880
Morning Peak     3904
Evening Peak     3904
Name: count, dtype: int64
============================================================

In [17]:
df = df.sort_values(

    [

        "Week",

        "Measurement_Site",

        "Vehicle_Category",

        "Time"

    ]

).reset_index(drop=True)

In [18]:
OUTPUT = PROJECT_DIR / "processed"

OUTPUT.mkdir(exist_ok=True)

df.to_csv(

    OUTPUT / "cleaned_dataset.csv",

    index=False

)

print("Clean dataset saved successfully!")

Clean dataset saved successfully!

In [19]:
df.head()

,Week,Measurement_Site,Latitude,Longitude,Source_File,Vehicle_Category,Time,von Unten nach Oben,von Links nach Oben,von Links nach Unten,von Oben nach Unten,Fahrtrichtung Süd-West,Fahrtrichtung Nord-Ost,Fahrtrichtung Nord-West,Fahrtrichtung Süd-Ost,Fahrtrichtung Nord-Ost.1,Fahrtrichtung Süd-West.1,von Rechts nach Unten,von Rechts nach Oben,Von Links nach Oben,Von Links nach Unten,Von Oben nach Unten,Fahrtrichtung Süd,Fahrtrichtung Nord,Fahrtrichtung West,Fahrtrichtung Ost,Leicht-rechts in Links,Rechts in Oben,Geradeaus in Links,Rechts in Oben.1,Falschfahrer,Falschfahrer.1,Falschfahrer.2,Geradeaus in Unten,Geradeaus in Oben,Fahrtrichtung Nord.1,Fahrtrichtung Süd.1,von Rechts Links nach Unten,von Links Geradeaus in Rechts,von Oben Links in Rechts,von Oben Geradeaus in Unten,von Unten Geradeaus in Oben,nach Unten,Total_Traffic,Hour,Minute,Peak_Period,Time_Interval
0,DZwEI 08.10-13.10,Glauburgstraße,50.127065,8.689309,2024-10-08_to_2024-10-13_UI_202403B0923.xlsx,Bus,1900-01-01 00:00:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,Off Peak,00:00
1,DZwEI 08.10-13.10,Glauburgstraße,50.127065,8.689309,2024-10-08_to_2024-10-13_UI_202403B0923.xlsx,Bus,1900-01-01 00:15:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,15,Off Peak,00:15
2,DZwEI 08.10-13.10,Glauburgstraße,50.127065,8.689309,2024-10-08_to_2024-10-13_UI_202403B0923.xlsx,Bus,1900-01-01 00:30:00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,30,Off Peak,00:30
3,DZwEI 08.10-13.10,Glauburgstraße,50.127065,8.689309,2024-10-08_to_2024-10-13_UI_202403B0923.xlsx,Bus,1900-01-01 00:45:00,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0,45,Off Peak,00:45
4,DZwEI 08.10-13.10,Glauburgstraße,50.127065,8.689309,2024-10-08_to_2024-10-13_UI_202403B0923.xlsx,Bus,1900-01-01 01:00:00,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,1,0,Off Peak,01:00