In [1]:
import pandas as pd
from pathlib import Path
import os

In [2]:
PROJECT_DIR = Path.cwd().parent

DATA_FOLDER = PROJECT_DIR / "Extracted_Data"

OUTPUT_FOLDER = PROJECT_DIR / "processed"

OUTPUT_FOLDER.mkdir(exist_ok=True)

In [3]:
excel_files = list(DATA_FOLDER.rglob("*.xlsx"))

print("Total Excel Files :", len(excel_files))

Total Excel Files : 24

In [4]:
excel_files = list(DATA_FOLDER.rglob("*.xlsx"))

print("Total Excel Files :", len(excel_files))

Total Excel Files : 24

In [6]:
sample = excel_files[0]

print(sample)

df = pd.read_excel(sample)

df.head()

c:\Users\vikhy\Desktop\Nikitha project\Extracted_Data\DZwEI 30.09-07.10\DZwEI 30.09-07.10\Friedberger Tor\2024-09-30_to_2024-10-07_UI_202403B0924.xlsx

,Name der Erhebung,Unnamed: 1,UI_202403B0924,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Geräte-UUID(s),NaN,9a97153e-ff0d-4897-ba03-5c483d07634d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Zähldatum,NaN,"Mon, 30. Sep 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Gesamt-Kfz,NaN,NaN,NaN,NaN
2,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
3,Standort,NaN,"(50.118,8.688)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
4,Gesamt-Kfz,NaN,"Pkw, Pkw mit Anhänger, Kraftrad, Lieferwagen, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN

In [7]:
df.head()

,Name der Erhebung,Unnamed: 1,UI_202403B0924,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Geräte-UUID(s),NaN,9a97153e-ff0d-4897-ba03-5c483d07634d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Zähldatum,NaN,"Mon, 30. Sep 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,von,nach,Wert,Spitzenzeit von Gesamt-Kfz,NaN,NaN,NaN,NaN
2,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
3,Standort,NaN,"(50.118,8.688)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
4,Gesamt-Kfz,NaN,"Pkw, Pkw mit Anhänger, Kraftrad, Lieferwagen, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN

In [8]:
print(df.columns.tolist())

['Name der Erhebung', 'Unnamed: 1', 'UI_202403B0924', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22']

In [9]:
import pandas as pd

sample = excel_files[0]

# Read the first 40 rows without assuming a header
df = pd.read_excel(sample, header=None)

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

display(df.head(40))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22
0,Name der Erhebung,NaN,UI_202403B0924,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geräte-UUID(s),NaN,9a97153e-ff0d-4897-ba03-5c483d07634d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Zähldatum,NaN,"Mon, 30. Sep 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,von,nach,Wert,Spitzenzeit von Gesamt-Kfz,NaN,NaN,NaN,NaN
3,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
4,Standort,NaN,"(50.118,8.688)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
5,Gesamt-Kfz,NaN,"Pkw, Pkw mit Anhänger, Kraftrad, Lieferwagen, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,von Rechts,von Links,von Oben,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rechts,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Startzeit,von Rechts Links nach Unten,von Links Geradeaus in Rechts,von Oben Links in Rechts,von Oben Geradeaus in Unten,NaN,NaN,Intervall,Summe Stunde,NaN,NaN,NaN,NaN,NaN,Fahrtrichtung Süd,Fahrtrichtung Nord,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q,Fahrtrichtung Süd-Ost,Fahrtrichtung Nord-West,Q
12,00:00:00,5,43,9,17,NaN,NaN,74,0,NaN,NaN,NaN,NaN,NaN,5,52,0,43,0,0,26,0,0
13,00:15:00,4,31,15,14,NaN,NaN,64,0,NaN,NaN,NaN,NaN,NaN,4,46,0,31,0,0,29,0,0
14,00:30:00,5,35,7,23,NaN,NaN,70,0,NaN,NaN,NaN,NaN,NaN,5,42,0,35,0,0,30,0,0
15,00:45:00,4,36,4,15,NaN,NaN,59,0,NaN,NaN,NaN,NaN,NaN,4,40,0,36,0,0,19,0,0
16,01:00:00,6,15,7,15,NaN,NaN,43,0,NaN,NaN,NaN,NaN,NaN,6,22,0,15,0,0,22,0,0
17,01:15:00,3,21,7,17,NaN,NaN,48,0,NaN,NaN,NaN,NaN,NaN,3,28,0,21,0,0,24,0,0
18,01:30:00,4,19,9,8,NaN,NaN,40,0,NaN,NaN,NaN,NaN,NaN,4,28,0,19,0,0,17,0,0
19,01:45:00,5,23,3,9,NaN,NaN,40,0,NaN,NaN,NaN,NaN,NaN,5,26,0,23,0,0,12,0,0
20,02:00:00,5,14,10,8,NaN,NaN,37,0,NaN,NaN,NaN,NaN,NaN,5,24,0,14,0,0,18,0,0
21,02:15:00,3,12,7,6,NaN,NaN,28,0,NaN,NaN,NaN,NaN,NaN,3,19,0,12,0,0,13,0,0
22,02:30:00,4,11,8,7,NaN,NaN,30,0,NaN,NaN,NaN,NaN,NaN,4,19,0,11,0,0,15,0,0
23,02:45:00,2,9,6,10,NaN,NaN,27,0,NaN,NaN,NaN,NaN,NaN,2,15,0,9,0,0,16,0,0
24,03:00:00,1,5,7,9,NaN,NaN,22,0,NaN,NaN,NaN,NaN,NaN,1,12,0,5,0,0,16,0,0
25,03:15:00,3,12,5,7,NaN,NaN,27,0,NaN,NaN,NaN,NaN,NaN,3,17,0,12,0,0,12,0,0
26,03:30:00,4,11,7,4,NaN,NaN,26,0,NaN,NaN,NaN,NaN,NaN,4,18,0,11,0,0,11,0,0
27,03:45:00,0,11,3,8,NaN,NaN,22,0,NaN,NaN,NaN,NaN,NaN,0,14,0,11,0,0,11,0,0
28,04:00:00,2,9,5,7,NaN,NaN,23,0,NaN,NaN,NaN,NaN,NaN,2,14,0,9,0,0,12,0,0
29,04:15:00,2,6,5,6,NaN,NaN,19,0,NaN,NaN,NaN,NaN,NaN,2,11,0,6,0,0,11,0,0
30,04:30:00,3,8,3,7,NaN,NaN,21,0,NaN,NaN,NaN,NaN,NaN,3,11,0,8,0,0,10,0,0
31,04:45:00,3,6,5,6,NaN,NaN,20,0,NaN,NaN,NaN,NaN,NaN,3,11,0,6,0,0,11,0,0
32,05:00:00,7,13,6,17,NaN,NaN,43,0,NaN,NaN,NaN,NaN,NaN,7,19,0,13,0,0,23,0,0
33,05:15:00,6,8,3,15,NaN,NaN,32,0,NaN,NaN,NaN,NaN,NaN,6,11,0,8,0,0,18,0,0
34,05:30:00,20,23,2,23,NaN,NaN,68,0,NaN,NaN,NaN,NaN,NaN,20,25,0,23,0,0,25,0,0
35,05:45:00,11,25,7,28,NaN,NaN,71,0,NaN,NaN,NaN,NaN,NaN,11,32,0,25,0,0,35,0,0
36,06:00:00,22,32,10,35,NaN,NaN,99,0,NaN,NaN,NaN,NaN,NaN,22,42,0,32,0,0,45,0,0
37,06:15:00,16,47,8,35,NaN,NaN,106,0,NaN,NaN,NaN,NaN,NaN,16,55,0,47,0,0,43,0,0
38,06:30:00,37,44,15,39,NaN,NaN,135,0,NaN,NaN,NaN,NaN,NaN,37,59,0,44,0,0,54,0,0
39,06:45:00,26,80,18,70,NaN,NaN,194,0,NaN,NaN,NaN,NaN,NaN,26,98,0,80,0,0,88,0,0

In [11]:
pd.read_excel(sample)

,Name der Erhebung,Unnamed: 1,UI_202403B0924,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Geräte-UUID(s),NaN,9a97153e-ff0d-4897-ba03-5c483d07634d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Zähldatum,NaN,"Mon, 30. Sep 2024",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,von,nach,Wert,Spitzenzeit von Gesamt-Kfz,NaN,NaN,NaN,NaN
2,Startzeit,NaN,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tagesspitze,00:00:00,23:59:59,0,0,NaN,NaN,NaN,NaN
3,Standort,NaN,"(50.118,8.688)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Morgenspitze,06:00:00,10:00:00,0,0,NaN,NaN,NaN,NaN
4,Gesamt-Kfz,NaN,"Pkw, Pkw mit Anhänger, Kraftrad, Lieferwagen, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abendspitze,15:00:00,19:00:00,0,0,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tagesverkehr,06:00:00,22:00:00,0,0,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nachtverkehr,22:00:00,06:00:00,0,0,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,von Rechts,von Links,von Oben,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Rechts,NaN,NaN,Links,NaN,NaN,Oben,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Startzeit,von Rechts Links nach Unten,von Links Geradeaus in Rechts,von Oben Links in Rechts,von Oben Geradeaus in Unten,NaN,NaN,Intervall,Summe Stunde,NaN,NaN,NaN,NaN,NaN,Fahrtrichtung Süd,Fahrtrichtung Nord,Q,Fahrtrichtung Nord-Ost,Fahrtrichtung Süd-West,Q,Fahrtrichtung Süd-Ost,Fahrtrichtung Nord-West,Q
11,00:00:00,5,43,9,17,NaN,NaN,74,0,NaN,NaN,NaN,NaN,NaN,5,52,0,43,0,0,26,0,0
12,00:15:00,4,31,15,14,NaN,NaN,64,0,NaN,NaN,NaN,NaN,NaN,4,46,0,31,0,0,29,0,0
13,00:30:00,5,35,7,23,NaN,NaN,70,0,NaN,NaN,NaN,NaN,NaN,5,42,0,35,0,0,30,0,0
14,00:45:00,4,36,4,15,NaN,NaN,59,0,NaN,NaN,NaN,NaN,NaN,4,40,0,36,0,0,19,0,0
15,01:00:00,6,15,7,15,NaN,NaN,43,0,NaN,NaN,NaN,NaN,NaN,6,22,0,15,0,0,22,0,0
16,01:15:00,3,21,7,17,NaN,NaN,48,0,NaN,NaN,NaN,NaN,NaN,3,28,0,21,0,0,24,0,0
17,01:30:00,4,19,9,8,NaN,NaN,40,0,NaN,NaN,NaN,NaN,NaN,4,28,0,19,0,0,17,0,0
18,01:45:00,5,23,3,9,NaN,NaN,40,0,NaN,NaN,NaN,NaN,NaN,5,26,0,23,0,0,12,0,0
19,02:00:00,5,14,10,8,NaN,NaN,37,0,NaN,NaN,NaN,NaN,NaN,5,24,0,14,0,0,18,0,0
20,02:15:00,3,12,7,6,NaN,NaN,28,0,NaN,NaN,NaN,NaN,NaN,3,19,0,12,0,0,13,0,0
21,02:30:00,4,11,8,7,NaN,NaN,30,0,NaN,NaN,NaN,NaN,NaN,4,19,0,11,0,0,15,0,0
22,02:45:00,2,9,6,10,NaN,NaN,27,0,NaN,NaN,NaN,NaN,NaN,2,15,0,9,0,0,16,0,0
23,03:00:00,1,5,7,9,NaN,NaN,22,0,NaN,NaN,NaN,NaN,NaN,1,12,0,5,0,0,16,0,0
24,03:15:00,3,12,5,7,NaN,NaN,27,0,NaN,NaN,NaN,NaN,NaN,3,17,0,12,0,0,12,0,0
25,03:30:00,4,11,7,4,NaN,NaN,26,0,NaN,NaN,NaN,NaN,NaN,4,18,0,11,0,0,11,0,0
26,03:45:00,0,11,3,8,NaN,NaN,22,0,NaN,NaN,NaN,NaN,NaN,0,14,0,11,0,0,11,0,0
27,04:00:00,2,9,5,7,NaN,NaN,23,0,NaN,NaN,NaN,NaN,NaN,2,14,0,9,0,0,12,0,0
28,04:15:00,2,6,5,6,NaN,NaN,19,0,NaN,NaN,NaN,NaN,NaN,2,11,0,6,0,0,11,0,0
29,04:30:00,3,8,3,7,NaN,NaN,21,0,NaN,NaN,NaN,NaN,NaN,3,11,0,8,0,0,10,0,0
30,04:45:00,3,6,5,6,NaN,NaN,20,0,NaN,NaN,NaN,NaN,NaN,3,11,0,6,0,0,11,0,0
31,05:00:00,7,13,6,17,NaN,NaN,43,0,NaN,NaN,NaN,NaN,NaN,7,19,0,13,0,0,23,0,0
32,05:15:00,6,8,3,15,NaN,NaN,32,0,NaN,NaN,NaN,NaN,NaN,6,11,0,8,0,0,18,0,0
33,05:30:00,20,23,2,23,NaN,NaN,68,0,NaN,NaN,NaN,NaN,NaN,20,25,0,23,0,0,25,0,0
34,05:45:00,11,25,7,28,NaN,NaN,71,0,NaN,NaN,NaN,NaN,NaN,11,32,0,25,0,0,35,0,0
35,06:00:00,22,32,10,35,NaN,NaN,99,0,NaN,NaN,NaN,NaN,NaN,22,42,0,32,0,0,45,0,0
36,06:15:00,16,47,8,35,NaN,NaN,106,0,NaN,NaN,NaN,NaN,NaN,16,55,0,47,0,0,43,0,0
37,06:30:00,37,44,15,39,NaN,NaN,135,0,NaN,NaN,NaN,NaN,NaN,37,59,0,44,0,0,54,0,0
38,06:45:00,26,80,18,70,NaN,NaN,194,0,NaN,NaN,NaN,NaN,NaN,26,98,0,80,0,0,88,0,0
39,07:00:00,32,62,18,82,NaN,NaN,194,0,NaN,NaN,NaN,NaN,NaN,32,80,0,62,0,0,100,0,0
40,07:15:00,32,83,32,75,NaN,NaN,222,0,NaN,NaN,NaN,NaN,NaN,32,115,0,83,0,0,107,0,0
41,07:30:00,43,98,40,126,NaN,NaN,307,0,NaN,NaN,NaN,NaN,NaN,43,138,0,98,0,0,166,0,0
42,07:45:00,41,128,39,119,NaN,NaN,327,0,NaN,NaN,NaN,NaN,NaN,41,167,0,128,0,0,158,0,0
43,08:00:00,36,110,41,142,NaN,NaN,329,0,NaN,NaN,NaN,NaN,NaN,36,151,0,110,0,0,183,0,0
44,08:15:00,46,97,41,145,NaN,NaN,329,0,NaN,NaN,NaN,NaN,NaN,46,138,0,97,0,0,186,0,0
45,08:30:00,32,112,20,125,NaN,NaN,289,0,NaN,NaN,NaN,NaN,NaN,32,132,0,112,0,0,145,0,0
46,08:45:00,47,112,29,99,NaN,NaN,287,0,NaN,NaN,NaN,NaN,NaN,47,141,0,112,0,0,128,0,0
47,09:00:00,35,109,39,128,NaN,NaN,311,0,NaN,NaN,NaN,NaN,NaN,35,148,0,109,0,0,167,0,0
48,09:15:00,36,113,41,96,NaN,NaN,286,0,NaN,NaN,NaN,NaN,NaN,36,154,0,113,0,0,137,0,0
49,09:30:00,36,100,33,128,NaN,NaN,297,0,NaN,NaN,NaN,NaN,NaN,36,133,0,100,0,0,161,0,0
50,09:45:00,34,104,28,98,NaN,NaN,264,0,NaN,NaN,NaN,NaN,NaN,34,132,0,104,0,0,126,0,0
51,10:00:00,34,99,44,106,NaN,NaN,283,0,NaN,NaN,NaN,NaN,NaN,34,143,0,99,0,0,150,0,0
52,10:15:00,43,129,30,121,NaN,NaN,323,0,NaN,NaN,NaN,NaN,NaN,43,159,0,129,0,0,151,0,0
53,10:30:00,36,93,33,104,NaN,NaN,266,0,NaN,NaN,NaN,NaN,NaN,36,126,0,93,0,0,137,0,0
54,10:45:00,45,123,44,108,NaN,NaN,320,0,NaN,NaN,NaN,NaN,NaN,45,167,0,123,0,0,152,0,0
55,11:00:00,55,126,41,127,NaN,NaN,349,0,NaN,NaN,NaN,NaN,NaN,55,167,0,126,0,0,168,0,0
56,11:15:00,40,134,47,103,NaN,NaN,324,0,NaN,NaN,NaN,NaN,NaN,40,181,0,134,0,0,150,0,0
57,11:30:00,40,144,40,118,NaN,NaN,342,0,NaN,NaN,NaN,NaN,NaN,40,184,0,144,0,0,158,0,0
58,11:45:00,47,156,47,133,NaN,NaN,383,0,NaN,NaN,NaN,NaN,NaN,47,203,0,156,0,0,180,0,0
59,12:00:00,41,141,49,131,NaN,NaN,362,0,NaN,NaN,NaN,NaN,NaN,41,190,0,141,0,0,180,0,0
60,12:15:00,37,139,43,129,NaN,NaN,348,0,NaN,NaN,NaN,NaN,NaN,37,182,0,139,0,0,172,0,0
61,12:30:00,32,158,44,130,NaN,NaN,364,0,NaN,NaN,NaN,NaN,NaN,32,202,0,158,0,0,174,0,0
62,12:45:00,32,169,48,113,NaN,NaN,362,0,NaN,NaN,NaN,NaN,NaN,32,217,0,169,0,0,161,0,0
63,13:00:00,43,150,58,143,NaN,NaN,394,0,NaN,NaN,NaN,NaN,NaN,43,208,0,150,0,0,201,0,0
64,13:15:00,51,139,61,142,NaN,NaN,393,0,NaN,NaN,NaN,NaN,NaN,51,200,0,139,0,0,203,0,0
65,13:30:00,37,169,62,139,NaN,NaN,407,0,NaN,NaN,NaN,NaN,NaN,37,231,0,169,0,0,201,0,0
66,13:45:00,45,123,65,153,NaN,NaN,386,0,NaN,NaN,NaN,NaN,NaN,45,188,0,123,0,0,218,0,0
67,14:00:00,43,150,59,148,NaN,NaN,400,0,NaN,NaN,NaN,NaN,NaN,43,209,0,150,0,0,207,0,0
68,14:15:00,26,152,70,146,NaN,NaN,394,0,NaN,NaN,NaN,NaN,NaN,26,222,0,152,0,0,216,0,0
69,14:30:00,37,146,61,148,NaN,NaN,392,0,NaN,NaN,NaN,NaN,NaN,37,207,0,146,0,0,209,0,0
70,14:45:00,37,155,59,150,NaN,NaN,401,0,NaN,NaN,NaN,NaN,NaN,37,214,0,155,0,0,209,0,0
71,15:00:00,21,108,45,98,NaN,NaN,272,0,NaN,NaN,NaN,NaN,NaN,21,153,0,108,0,0,143,0,0
72,15:15:00,24,169,70,138,NaN,NaN,401,0,NaN,NaN,NaN,NaN,NaN,24,239,0,169,0,0,208,0,0
73,15:30:00,32,166,63,163,NaN,NaN,424,0,NaN,NaN,NaN,NaN,NaN,32,229,0,166,0,0,226,0,0
74,15:45:00,35,170,49,169,NaN,NaN,423,0,NaN,NaN,NaN,NaN,NaN,35,219,0,170,0,0,218,0,0
75,16:00:00,36,131,52,169,NaN,NaN,388,0,NaN,NaN,NaN,NaN,NaN,36,183,0,131,0,0,221,0,0
76,16:15:00,30,176,60,172,NaN,NaN,438,0,NaN,NaN,NaN,NaN,NaN,30,236,0,176,0,0,232,0,0
77,16:30:00,20,160,68,180,NaN,NaN,428,0,NaN,NaN,NaN,NaN,NaN,20,228,0,160,0,0,248,0,0
78,16:45:00,30,161,67,181,NaN,NaN,439,0,NaN,NaN,NaN,NaN,NaN,30,228,0,161,0,0,248,0,0
79,17:00:00,22,158,62,179,NaN,NaN,421,0,NaN,NaN,NaN,NaN,NaN,22,220,0,158,0,0,241,0,0
80,17:15:00,31,173,74,183,NaN,NaN,461,0,NaN,NaN,NaN,NaN,NaN,31,247,0,173,0,0,257,0,0
81,17:30:00,30,154,81,174,NaN,NaN,439,0,NaN,NaN,NaN,NaN,NaN,30,235,0,154,0,0,255,0,0
82,17:45:00,36,180,65,182,NaN,NaN,463,0,NaN,NaN,NaN,NaN,NaN,36,245,0,180,0,0,247,0,0
83,18:00:00,41,147,73,166,NaN,NaN,427,0,NaN,NaN,NaN,NaN,NaN,41,220,0,147,0,0,239,0,0
84,18:15:00,36,152,58,169,NaN,NaN,415,0,NaN,NaN,NaN,NaN,NaN,36,210,0,152,0,0,227,0,0
85,18:30:00,36,161,49,153,NaN,NaN,399,0,NaN,NaN,NaN,NaN,NaN,36,210,0,161,0,0,202,0,0
86,18:45:00,33,161,55,135,NaN,NaN,384,0,NaN,NaN,NaN,NaN,NaN,33,216,0,161,0,0,190,0,0
87,19:00:00,26,119,70,125,NaN,NaN,340,0,NaN,NaN,NaN,NaN,NaN,26,189,0,119,0,0,195,0,0
88,19:15:00,29,138,50,115,NaN,NaN,332,0,NaN,NaN,NaN,NaN,NaN,29,188,0,138,0,0,165,0,0
89,19:30:00,23,103,53,125,NaN,NaN,304,0,NaN,NaN,NaN,NaN,NaN,23,156,0,103,0,0,178,0,0
90,19:45:00,31,111,30,110,NaN,NaN,282,0,NaN,NaN,NaN,NaN,NaN,31,141,0,111,0,0,140,0,0
91,20:00:00,26,144,43,106,NaN,NaN,319,0,NaN,NaN,NaN,NaN,NaN,26,187,0,144,0,0,149,0,0
92,20:15:00,21,103,38,115,NaN,NaN,277,0,NaN,NaN,NaN,NaN,NaN,21,141,0,103,0,0,153,0,0
93,20:30:00,28,102,37,79,NaN,NaN,246,0,NaN,NaN,NaN,NaN,NaN,28,139,0,102,0,0,116,0,0
94,20:45:00,15,102,35,64,NaN,NaN,216,0,NaN,NaN,NaN,NaN,NaN,15,137,0,102,0,0,99,0,0
95,21:00:00,26,96,38,77,NaN,NaN,237,0,NaN,NaN,NaN,NaN,NaN,26,134,0,96,0,0,115,0,0
96,21:15:00,15,84,28,60,NaN,NaN,187,0,NaN,NaN,NaN,NaN,NaN,15,112,0,84,0,0,88,0,0
97,21:30:00,19,75,41,58,NaN,NaN,193,0,NaN,NaN,NaN,NaN,NaN,19,116,0,75,0,0,99,0,0
98,21:45:00,18,68,36,73,NaN,NaN,195,0,NaN,NaN,NaN,NaN,NaN,18,104,0,68,0,0,109,0,0
99,22:00:00,15,72,28,65,NaN,NaN,180,0,NaN,NaN,NaN,NaN,NaN,15,100,0,72,0,0,93,0,0
100,22:15:00,19,65,34,75,NaN,NaN,193,0,NaN,NaN,NaN,NaN,NaN,19,99,0,65,0,0,109,0,0
101,22:30:00,19,78,29,71,NaN,NaN,197,0,NaN,NaN,NaN,NaN,NaN,19,107,0,78,0,0,100,0,0
102,22:45:00,12,55,32,43,NaN,NaN,142,0,NaN,NaN,NaN,NaN,NaN,12,87,0,55,0,0,75,0,0
103,23:00:00,10,63,18,46,NaN,NaN,137,0,NaN,NaN,NaN,NaN,NaN,10,81,0,63,0,0,64,0,0
104,23:15:00,8,42,19,39,NaN,NaN,108,0,NaN,NaN,NaN,NaN,NaN,8,61,0,42,0,0,58,0,0
105,23:30:00,10,37,16,28,NaN,NaN,91,0,NaN,NaN,NaN,NaN,NaN,10,53,0,37,0,0,44,0,0
106,23:45:00,10,36,14,33,NaN,NaN,93,0,NaN,NaN,NaN,NaN,NaN,10,50,0,36,0,0,47,0,0
107,00:00:00,8,47,19,28,NaN,NaN,102,0,NaN,NaN,NaN,NaN,NaN,8,66,0,47,0,0,47,0,0
108,00:15:00,6,28,14,17,NaN,NaN,65,0,NaN,NaN,NaN,NaN,NaN,6,42,0,28,0,0,31,0,0
109,00:30:00,6,37,15,19,NaN,NaN,77,0,NaN,NaN,NaN,NaN,NaN,6,52,0,37,0,0,34,0,0
110,00:45:00,5,31,10,21,NaN,NaN,67,0,NaN,NaN,NaN,NaN,NaN,5,41,0,31,0,0,31,0,0
111,01:00:00,2,23,9,17,NaN,NaN,51,0,NaN,NaN,NaN,NaN,NaN,2,32,0,23,0,0,26,0,0
112,01:15:00,3,19,9,10,NaN,NaN,41,0,NaN,NaN,NaN,NaN,NaN,3,28,0,19,0,0,19,0,0
113,01:30:00,1,17,8,9,NaN,NaN,35,0,NaN,NaN,NaN,NaN,NaN,1,25,0,17,0,0,17,0,0
114,01:45:00,3,12,5,11,NaN,NaN,31,0,NaN,NaN,NaN,NaN,NaN,3,17,0,12,0,0,16,0,0
115,02:00:00,4,15,11,11,NaN,NaN,41,0,NaN,NaN,NaN,NaN,NaN,4,26,0,15,0,0,22,0,0
116,02:15:00,2,12,9,9,NaN,NaN,32,0,NaN,NaN,NaN,NaN,NaN,2,21,0,12,0,0,18,0,0
117,02:30:00,4,14,10,6,NaN,NaN,34,0,NaN,NaN,NaN,NaN,NaN,4,24,0,14,0,0,16,0,0
118,02:45:00,1,5,3,5,NaN,NaN,14,0,NaN,NaN,NaN,NaN,NaN,1,8,0,5,0,0,8,0,0
119,03:00:00,3,12,7,4,NaN,NaN,26,0,NaN,NaN,NaN,NaN,NaN,3,19,0,12,0,0,11,0,0
120,03:15:00,0,7,3,9,NaN,NaN,19,0,NaN,NaN,NaN,NaN,NaN,0,10,0,7,0,0,12,0,0
121,03:30:00,4,11,7,6,NaN,NaN,28,0,NaN,NaN,NaN,NaN,NaN,4,18,0,11,0,0,13,0,0
122,03:45:00,0,8,5,5,NaN,NaN,18,0,NaN,NaN,NaN,NaN,NaN,0,13,0,8,0,0,10,0,0
123,04:00:00,1,10,5,4,NaN,NaN,20,0,NaN,NaN,NaN,NaN,NaN,1,15,0,10,0,0,9,0,0
124,04:15:00,1,7,7,11,NaN,NaN,26,0,NaN,NaN,NaN,NaN,NaN,1,14,0,7,0,0,18,0,0
125,04:30:00,3,10,4,3,NaN,NaN,20,0,NaN,NaN,NaN,NaN,NaN,3,14,0,10,0,0,7,0,0
126,04:45:00,3,12,2,13,NaN,NaN,30,0,NaN,NaN,NaN,NaN,NaN,3,14,0,12,0,0,15,0,0
127,05:00:00,2,10,7,11,NaN,NaN,30,0,NaN,NaN,NaN,NaN,NaN,2,17,0,10,0,0,18,0,0
128,05:15:00,6,15,4,17,NaN,NaN,42,0,NaN,NaN,NaN,NaN,NaN,6,19,0,15,0,0,21,0,0
129,05:30:00,12,16,7,27,NaN,NaN,62,0,NaN,NaN,NaN,NaN,NaN,12,23,0,16,0,0,34,0,0
130,05:45:00,21,29,7,40,NaN,NaN,97,0,NaN,NaN,NaN,NaN,NaN,21,36,0,29,0,0,47,0,0
131,06:00:00,13,33,10,44,NaN,NaN,100,0,NaN,NaN,NaN,NaN,NaN,13,43,0,33,0,0,54,0,0
132,06:15:00,24,40,7,38,NaN,NaN,109,0,NaN,NaN,NaN,NaN,NaN,24,47,0,40,0,0,45,0,0
133,06:30:00,23,52,13,55,NaN,NaN,143,0,NaN,NaN,NaN,NaN,NaN,23,65,0,52,0,0,68,0,0
134,06:45:00,16,57,26,59,NaN,NaN,158,0,NaN,NaN,NaN,NaN,NaN,16,83,0,57,0,0,85,0,0
135,07:00:00,29,52,30,68,NaN,NaN,179,0,NaN,NaN,NaN,NaN,NaN,29,82,0,52,0,0,98,0,0
136,07:15:00,27,97,27,81,NaN,NaN,232,0,NaN,NaN,NaN,NaN,NaN,27,124,0,97,0,0,108,0,0
137,07:30:00,45,92,29,104,NaN,NaN,270,0,NaN,NaN,NaN,NaN,NaN,45,121,0,92,0,0,133,0,0
138,07:45:00,40,125,32,106,NaN,NaN,303,0,NaN,NaN,NaN,NaN,NaN,40,157,0,125,0,0,138,0,0
139,08:00:00,39,107,38,143,NaN,NaN,327,0,NaN,NaN,NaN,NaN,NaN,39,145,0,107,0,0,181,0,0
140,08:15:00,54,110,31,127,NaN,NaN,322,0,NaN,NaN,NaN,NaN,NaN,54,141,0,110,0,0,158,0,0
141,08:30:00,49,104,22,122,NaN,NaN,297,0,NaN,NaN,NaN,NaN,NaN,49,126,0,104,0,0,144,0,0
142,08:45:00,41,107,29,117,NaN,NaN,294,0,NaN,NaN,NaN,NaN,NaN,41,136,0,107,0,0,146,0,0
143,09:00:00,39,88,36,111,NaN,NaN,274,0,NaN,NaN,NaN,NaN,NaN,39,124,0,88,0,0,147,0,0
144,09:15:00,45,125,29,118,NaN,NaN,317,0,NaN,NaN,NaN,NaN,NaN,45,154,0,125,0,0,147,0,0
145,09:30:00,49,110,26,102,NaN,NaN,287,0,NaN,NaN,NaN,NaN,NaN,49,136,0,110,0,0,128,0,0
146,09:45:00,59,114,30,116,NaN,NaN,319,0,NaN,NaN,NaN,NaN,NaN,59,144,0,114,0,0,146,0,0
147,10:00:00,54,126,31,117,NaN,NaN,328,0,NaN,NaN,NaN,NaN,NaN,54,157,0,126,0,0,148,0,0
148,10:15:00,43,101,32,116,NaN,NaN,292,0,NaN,NaN,NaN,NaN,NaN,43,133,0,101,0,0,148,0,0
149,10:30:00,41,99,29,111,NaN,NaN,280,0,NaN,NaN,NaN,NaN,NaN,41,128,0,99,0,0,140,0,0
150,10:45:00,48,123,43,131,NaN,NaN,345,0,NaN,NaN,NaN,NaN,NaN,48,166,0,123,0,0,174,0,0
151,11:00:00,41,150,44,115,NaN,NaN,350,0,NaN,NaN,NaN,NaN,NaN,41,194,0,150,0,0,159,0,0
152,11:15:00,44,151,39,120,NaN,NaN,354,0,NaN,NaN,NaN,NaN,NaN,44,190,0,151,0,0,159,0,0
153,11:30:00,52,138,39,125,NaN,NaN,354,0,NaN,NaN,NaN,NaN,NaN,52,177,0,138,0,0,164,0,0
154,11:45:00,44,134,41,117,NaN,NaN,336,0,NaN,NaN,NaN,NaN,NaN,44,175,0,134,0,0,158,0,0
155,12:00:00,48,168,40,129,NaN,NaN,385,0,NaN,NaN,NaN,NaN,NaN,48,208,0,168,0,0,169,0,0
156,12:15:00,49,158,38,117,NaN,NaN,362,0,NaN,NaN,NaN,NaN,NaN,49,196,0,158,0,0,155,0,0
157,12:30:00,56,142,51,137,NaN,NaN,386,0,NaN,NaN,NaN,NaN,NaN,56,193,0,142,0,0,188,0,0
158,12:45:00,37,140,52,131,NaN,NaN,360,0,NaN,NaN,NaN,NaN,NaN,37,192,0,140,0,0,183,0,0
159,13:00:00,39,152,57,141,NaN,NaN,389,0,NaN,NaN,NaN,NaN,NaN,39,209,0,152,0,0,198,0,0
160,13:15:00,43,147,46,121,NaN,NaN,357,0,NaN,NaN,NaN,NaN,NaN,43,193,0,147,0,0,167,0,0
161,13:30:00,53,163,46,155,NaN,NaN,417,0,NaN,NaN,NaN,NaN,NaN,53,209,0,163,0,0,201,0,0
162,13:45:00,54,142,49,122,NaN,NaN,367,0,NaN,NaN,NaN,NaN,NaN,54,191,0,142,0,0,171,0,0
163,14:00:00,43,145,41,139,NaN,NaN,368,0,NaN,NaN,NaN,NaN,NaN,43,186,0,145,0,0,180,0,0
164,14:15:00,41,156,51,160,NaN,NaN,408,0,NaN,NaN,NaN,NaN,NaN,41,207,0,156,0,0,211,0,0
165,14:30:00,37,184,54,142,NaN,NaN,417,0,NaN,NaN,NaN,NaN,NaN,37,238,0,184,0,0,196,0,0
166,14:45:00,42,179,55,168,NaN,NaN,444,0,NaN,NaN,NaN,NaN,NaN,42,234,0,179,0,0,223,0,0
167,15:00:00,37,167,62,161,NaN,NaN,427,0,NaN,NaN,NaN,NaN,NaN,37,229,0,167,0,0,223,0,0
168,15:15:00,46,185,60,155,NaN,NaN,446,0,NaN,NaN,NaN,NaN,NaN,46,245,0,185,0,0,215,0,0
169,15:30:00,30,181,61,146,NaN,NaN,418,0,NaN,NaN,NaN,NaN,NaN,30,242,0,181,0,0,207,0,0
170,15:45:00,38,180,59,163,NaN,NaN,440,0,NaN,NaN,NaN,NaN,NaN,38,239,0,180,0,0,222,0,0
171,16:00:00,40,169,74,183,NaN,NaN,466,0,NaN,NaN,NaN,NaN,NaN,40,243,0,169,0,0,257,0,0
172,16:15:00,33,176,65,172,NaN,NaN,446,0,NaN,NaN,NaN,NaN,NaN,33,241,0,176,0,0,237,0,0
173,16:30:00,54,167,72,167,NaN,NaN,460,0,NaN,NaN,NaN,NaN,NaN,54,239,0,167,0,0,239,0,0
174,16:45:00,28,157,71,180,NaN,NaN,436,0,NaN,NaN,NaN,NaN,NaN,28,228,0,157,0,0,251,0,0
175,17:00:00,33,175,67,184,NaN,NaN,459,0,NaN,NaN,NaN,NaN,NaN,33,242,0,175,0,0,251,0,0
176,17:15:00,43,161,75,202,NaN,NaN,481,0,NaN,NaN,NaN,NaN,NaN,43,236,0,161,0,0,277,0,0
177,17:30:00,40,178,66,178,NaN,NaN,462,0,NaN,NaN,NaN,NaN,NaN,40,244,0,178,0,0,244,0,0
178,17:45:00,27,170,66,217,NaN,NaN,480,0,NaN,NaN,NaN,NaN,NaN,27,236,0,170,0,0,283,0,0
179,18:00:00,29,157,63,193,NaN,NaN,442,0,NaN,NaN,NaN,NaN,NaN,29,220,0,157,0,0,256,0,0
180,18:15:00,30,179,66,180,NaN,NaN,455,0,NaN,NaN,NaN,NaN,NaN,30,245,0,179,0,0,246,0,0
181,18:30:00,41,165,66,179,NaN,NaN,451,0,NaN,NaN,NaN,NaN,NaN,41,231,0,165,0,0,245,0,0
182,18:45:00,35,162,58,139,NaN,NaN,394,0,NaN,NaN,NaN,NaN,NaN,35,220,0,162,0,0,197,0,0
183,19:00:00,35,149,66,157,NaN,NaN,407,0,NaN,NaN,NaN,NaN,NaN,35,215,0,149,0,0,223,0,0
184,19:15:00,31,143,70,135,NaN,NaN,379,0,NaN,NaN,NaN,NaN,NaN,31,213,0,143,0,0,205,0,0
185,19:30:00,41,104,56,122,NaN,NaN,323,0,NaN,NaN,NaN,NaN,NaN,41,160,0,104,0,0,178,0,0
186,19:45:00,36,130,45,109,NaN,NaN,320,0,NaN,NaN,NaN,NaN,NaN,36,175,0,130,0,0,154,0,0
187,20:00:00,41,113,58,102,NaN,NaN,314,0,NaN,NaN,NaN,NaN,NaN,41,171,0,113,0,0,160,0,0
188,20:15:00,27,132,42,116,NaN,NaN,317,0,NaN,NaN,NaN,NaN,NaN,27,174,0,132,0,0,158,0,0
189,20:30:00,24,105,40,89,NaN,NaN,258,0,NaN,NaN,NaN,NaN,NaN,24,145,0,105,0,0,129,0,0
190,20:45:00,22,107,47,106,NaN,NaN,282,0,NaN,NaN,NaN,NaN,NaN,22,154,0,107,0,0,153,0,0
191,21:00:00,28,104,38,79,NaN,NaN,249,0,NaN,NaN,NaN,NaN,NaN,28,142,0,104,0,0,117,0,0
192,21:15:00,23,106,28,75,NaN,NaN,232,0,NaN,NaN,NaN,NaN,NaN,23,134,0,106,0,0,103,0,0
193,21:30:00,21,78,36,68,NaN,NaN,203,0,NaN,NaN,NaN,NaN,NaN,21,114,0,78,0,0,104,0,0
194,21:45:00,17,92,28,57,NaN,NaN,194,0,NaN,NaN,NaN,NaN,NaN,17,120,0,92,0,0,85,0,0
195,22:00:00,20,66,28,68,NaN,NaN,182,0,NaN,NaN,NaN,NaN,NaN,20,94,0,66,0,0,96,0,0
196,22:15:00,28,81,36,72,NaN,NaN,217,0,NaN,NaN,NaN,NaN,NaN,28,117,0,81,0,0,108,0,0
197,22:30:00,16,94,23,55,NaN,NaN,188,0,NaN,NaN,NaN,NaN,NaN,16,117,0,94,0,0,78,0,0
198,22:45:00,23,50,32,65,NaN,NaN,170,0,NaN,NaN,NaN,NaN,NaN,23,82,0,50,0,0,97,0,0
199,23:00:00,20,81,14,55,NaN,NaN,170,0,NaN,NaN,NaN,NaN,NaN,20,95,0,81,0,0,69,0,0
200,23:15:00,14,59,27,50,NaN,NaN,150,0,NaN,NaN,NaN,NaN,NaN,14,86,0,59,0,0,77,0,0
201,23:30:00,6,32,16,27,NaN,NaN,81,0,NaN,NaN,NaN,NaN,NaN,6,48,0,32,0,0,43,0,0
202,23:45:00,10,36,18,38,NaN,NaN,102,0,NaN,NaN,NaN,NaN,NaN,10,54,0,36,0,0,56,0,0
203,00:00:00,4,49,13,24,NaN,NaN,90,0,NaN,NaN,NaN,NaN,NaN,4,62,0,49,0,0,37,0,0
204,00:15:00,4,29,11,35,NaN,NaN,79,0,NaN,NaN,NaN,NaN,NaN,4,40,0,29,0,0,46,0,0
205,00:30:00,3,30,15,17,NaN,NaN,65,0,NaN,NaN,NaN,NaN,NaN,3,45,0,30,0,0,32,0,0
206,00:45:00,3,30,9,18,NaN,NaN,60,0,NaN,NaN,NaN,NaN,NaN,3,39,0,30,0,0,27,0,0
207,01:00:00,4,27,12,13,NaN,NaN,56,0,NaN,NaN,NaN,NaN,NaN,4,39,0,27,0,0,25,0,0
208,01:15:00,3,14,11,14,NaN,NaN,42,0,NaN,NaN,NaN,NaN,NaN,3,25,0,14,0,0,25,0,0
209,01:30:00,6,22,12,13,NaN,NaN,53,0,NaN,NaN,NaN,NaN,NaN,6,34,0,22,0,0,25,0,0
210,01:45:00,0,18,12,19,NaN,NaN,49,0,NaN,NaN,NaN,NaN,NaN,0,30,0,18,0,0,31,0,0
211,02:00:00,4,8,13,11,NaN,NaN,36,0,NaN,NaN,NaN,NaN,NaN,4,21,0,8,0,0,24,0,0
212,02:15:00,4,10,6,9,NaN,NaN,29,0,NaN,NaN,NaN,NaN,NaN,4,16,0,10,0,0,15,0,0
213,02:30:00,3,14,9,12,NaN,NaN,38,0,NaN,NaN,NaN,NaN,NaN,3,23,0,14,0,0,21,0,0
214,02:45:00,5,14,6,6,NaN,NaN,31,0,NaN,NaN,NaN,NaN,NaN,5,20,0,14,0,0,12,0,0
215,03:00:00,1,14,7,8,NaN,NaN,30,0,NaN,NaN,NaN,NaN,NaN,1,21,0,14,0,0,15,0,0
216,03:15:00,2,14,2,12,NaN,NaN,30,0,NaN,NaN,NaN,NaN,NaN,2,16,0,14,0,0,14,0,0
217,03:30:00,0,9,7,4,NaN,NaN,20,0,NaN,NaN,NaN,NaN,NaN,0,16,0,9,0,0,11,0,0
218,03:45:00,5,12,3,12,NaN,NaN,32,0,NaN,NaN,NaN,NaN,NaN,5,15,0,12,0,0,15,0,0
219,04:00:00,1,6,4,6,NaN,NaN,17,0,NaN,NaN,NaN,NaN,NaN,1,10,0,6,0,0,10,0,0
220,04:15:00,4,10,8,10,NaN,NaN,32,0,NaN,NaN,NaN,NaN,NaN,4,18,0,10,0,0,18,0,0
221,04:30:00,4,11,3,7,NaN,NaN,25,0,NaN,NaN,NaN,NaN,NaN,4,14,0,11,0,0,10,0,0
222,04:45:00,2,12,0,9,NaN,NaN,23,0,NaN,NaN,NaN,NaN,NaN,2,12,0,12,0,0,9,0,0
223,05:00:00,4,10,6,7,NaN,NaN,27,0,NaN,NaN,NaN,NaN,NaN,4,16,0,10,0,0,13,0,0
224,05:15:00,8,12,6,17,NaN,NaN,43,0,NaN,NaN,NaN,NaN,NaN,8,18,0,12,0,0,23,0,0
225,05:30:00,16,19,5,27,NaN,NaN,67,0,NaN,NaN,NaN,NaN,NaN,16,24,0,19,0,0,32,0,0
226,05:45:00,18,19,10,38,NaN,NaN,85,0,NaN,NaN,NaN,NaN,NaN,18,29,0,19,0,0,48,0,0
227,06:00:00,15,31,11,37,NaN,NaN,94,0,NaN,NaN,NaN,NaN,NaN,15,42,0,31,0,0,48,0,0
228,06:15:00,24,41,6,38,NaN,NaN,109,0,NaN,NaN,NaN,NaN,NaN,24,47,0,41,0,0,44,0,0
229,06:30:00,13,55,16,56,NaN,NaN,140,0,NaN,NaN,NaN,NaN,NaN,13,71,0,55,0,0,72,0,0
230,06:45:00,31,55,15,77,NaN,NaN,178,0,NaN,NaN,NaN,NaN,NaN,31,70,0,55,0,0,92,0,0
231,07:00:00,23,62,23,84,NaN,NaN,192,0,NaN,NaN,NaN,NaN,NaN,23,85,0,62,0,0,107,0,0
232,07:15:00,47,88,34,82,NaN,NaN,251,0,NaN,NaN,NaN,NaN,NaN,47,122,0,88,0,0,116,0,0
233,07:30:00,29,94,33,117,NaN,NaN,273,0,NaN,NaN,NaN,NaN,NaN,29,127,0,94,0,0,150,0,0

In [12]:
import pandas as pd

xls = pd.ExcelFile(sample)

print(xls.sheet_names)

['Gesamt-Kfz', 'SV >3.5t', 'LV <3.5t', 'Pkw', 'Pkw mit Anhänger', 'Lkw', 'Lkw mit Anhänger', 'Bus', 'Lieferwagen', 'Kraftrad', 'Sattel-Kfz', 'Erklärungen']

In [13]:
df.iloc[:35].to_csv("first35rows.csv", index=False)