In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

pd.set_option("display.max_columns", None)

In [3]:
PROJECT_DIR = Path.cwd().parent

DATA_PATH = PROJECT_DIR / "processed" / "master_dataset.csv"

df = pd.read_csv(DATA_PATH)

print(df.shape)

df.head()

(193596, 36)

,Week,Measurement_Site,Latitude,Longitude,Vehicle_Category,Source_File,Time,Direction_1,Direction_2,Direction_3,Direction_4,Direction_5,Direction_6,Direction_7,Direction_8,Direction_9,Direction_10,Direction_11,Direction_12,Direction_13,Direction_14,Direction_15,Direction_16,Direction_17,Direction_18,Direction_19,Direction_20,Direction_21,Direction_22,Direction_23,Direction_24,Direction_25,Direction_26,Direction_27,Direction_28,Total_Traffic
0,DZwEI 30.09-07.10,Friedberger Tor,NaN,NaN,Gesamt-Kfz,2024-09-30_to_2024-10-07_UI_202403B0924.xlsx,00:00:00,5,43.0,9.0,17.0,NaN,NaN,74.0,0.0,NaN,NaN,NaN,NaN,NaN,5.0,52.0,0.0,43.0,0.0,0.0,26.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,274.0
1,DZwEI 30.09-07.10,Friedberger Tor,NaN,NaN,Gesamt-Kfz,2024-09-30_to_2024-10-07_UI_202403B0924.xlsx,00:15:00,4,31.0,15.0,14.0,NaN,NaN,64.0,0.0,NaN,NaN,NaN,NaN,NaN,4.0,46.0,0.0,31.0,0.0,0.0,29.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,238.0
2,DZwEI 30.09-07.10,Friedberger Tor,NaN,NaN,Gesamt-Kfz,2024-09-30_to_2024-10-07_UI_202403B0924.xlsx,00:30:00,5,35.0,7.0,23.0,NaN,NaN,70.0,0.0,NaN,NaN,NaN,NaN,NaN,5.0,42.0,0.0,35.0,0.0,0.0,30.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,252.0
3,DZwEI 30.09-07.10,Friedberger Tor,NaN,NaN,Gesamt-Kfz,2024-09-30_to_2024-10-07_UI_202403B0924.xlsx,00:45:00,4,36.0,4.0,15.0,NaN,NaN,59.0,0.0,NaN,NaN,NaN,NaN,NaN,4.0,40.0,0.0,36.0,0.0,0.0,19.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,217.0
4,DZwEI 30.09-07.10,Friedberger Tor,NaN,NaN,Gesamt-Kfz,2024-09-30_to_2024-10-07_UI_202403B0924.xlsx,01:00:00,6,15.0,7.0,15.0,NaN,NaN,43.0,0.0,NaN,NaN,NaN,NaN,NaN,6.0,22.0,0.0,15.0,0.0,0.0,22.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,151.0

In [4]:
print("="*60)

print(df.info())

print("="*60)

print(df.describe(include="all"))

============================================================
<class 'pandas.DataFrame'>
RangeIndex: 193596 entries, 0 to 193595
Data columns (total 36 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Week              193596 non-null  str
 1   Measurement_Site  193596 non-null  str
 2   Latitude          64944 non-null   float64
 3   Longitude         64944 non-null   float64
 4   Vehicle_Category  193596 non-null  str
 5   Source_File       193596 non-null  str
 6   Time              191976 non-null  str
 7   Direction_1       191636 non-null  str
 8   Direction_2       175404 non-null  float64
 9   Direction_3       79024 non-null   float64
 10  Direction_4       95084 non-null   float64
 11  Direction_5       142690 non-null  float64
 12  Direction_6       110420 non-null  float64
 13  Direction_7       62546 non-null   float64
 14  Direction_8       62106 non-null   float64
 15  Direction_9       15774 non-null   float64
 16  Direction_10      15840 non-null   float64
 17  Direction_11      31636 non-null   float64
 18  Direction_12      103349 non-null  float64
 19  Direction_13      103349 non-null  float64
 20  Direction_14      134017 non-null  float64
 21  Direction_15      133727 non-null  float64
 22  Direction_16      133727 non-null  float64
 23  Direction_17      149589 non-null  float64
 24  Direction_18      78254 non-null   float64
 25  Direction_19      78254 non-null   float64
 26  Direction_20      78254 non-null   float64
 27  Direction_21      78254 non-null   float64
 28  Direction_22      78254 non-null   float64
 29  Direction_23      31724 non-null   float64
 30  Direction_24      15862 non-null   float64
 31  Direction_25      15862 non-null   float64
 32  Direction_26      15862 non-null   float64
 33  Direction_27      15862 non-null   float64
 34  Direction_28      15862 non-null   float64
 35  Total_Traffic     193596 non-null  float64
dtypes: float64(30), str(6)
memory usage: 70.8 MB
None
============================================================
                     Week    Measurement_Site      Latitude     Longitude  \
count              193596              193596  64944.000000  64944.000000
unique                  6                  11           NaN           NaN
top     DZwEI 14.10-22.10  Hanauer Landstraße           NaN           NaN
freq                38808               32472           NaN           NaN
mean                  NaN                 NaN     50.116645      8.693996
std                   NaN                 NaN      0.006028      0.007041
min                   NaN                 NaN     50.112563      8.685743
25%                   NaN                 NaN     50.113192      8.688417
50%                   NaN                 NaN     50.113475      8.693137
75%                   NaN                 NaN     50.116928      8.698715
max                   NaN                 NaN     50.127065      8.703965

       Vehicle_Category                                   Source_File    Time  \
count            193596                                        193596  191976
unique               15                                            24     150
top          Gesamt-Kfz  2024-10-14_to_2024-10-22_UI_202403B0923.xlsx       0
freq              17232                                          9702    2260
mean                NaN                                           NaN     NaN
std                 NaN                                           NaN     NaN
min                 NaN                                           NaN     NaN
25%                 NaN                                           NaN     NaN
50%                 NaN                                           NaN     NaN
75%                 NaN                                           NaN     NaN
max                 NaN                                           NaN     NaN

       Direction_1    Direction_2   Direction_3    Direction_4    Direction_5  \
count       191636  175404.000000  79024.000000   95084.000000  142690.000000
unique         450            NaN           NaN            NaN            NaN
top              0            NaN           NaN            NaN            NaN
freq        126187            NaN           NaN            NaN            NaN
mean           NaN      14.822838      7.902840      22.296832      21.483054
std            NaN     382.181723    343.744497     925.744198     164.111912
min            NaN       0.000000      0.000000       0.000000       0.000000
25%            NaN       0.000000      0.000000       0.000000       0.000000
50%            NaN       0.000000      0.000000       0.000000       0.000000
75%            NaN       1.000000      1.000000       3.000000       2.000000
max            NaN   86504.000000  57326.000000  168747.000000   17015.000000

          Direction_6   Direction_7   Direction_8  Direction_9  Direction_10  \
count   110420.000000  62546.000000  62106.000000      15774.0  15840.000000
unique            NaN           NaN           NaN          NaN           NaN
top               NaN           NaN           NaN          NaN           NaN
freq              NaN           NaN           NaN          NaN           NaN
mean        29.397147     20.421977      8.187856          0.0     66.563258
std        202.022861     64.935729     33.361093          0.0    157.645917
min          0.000000      0.000000      0.000000          0.0      0.000000
25%          0.000000      0.000000      0.000000          0.0      0.000000
50%          0.000000      0.000000      0.000000          0.0      1.000000
75%          0.000000      2.000000      0.000000          0.0     13.000000
max       2444.000000    498.000000    248.000000          0.0    806.000000

        Direction_11   Direction_12   Direction_13   Direction_14  \
count   31636.000000  103349.000000  103349.000000  134017.000000
unique           NaN            NaN            NaN            NaN
top              NaN            NaN            NaN            NaN
freq             NaN            NaN            NaN            NaN
mean      100.260178      14.347115       6.385674       4.335726
std       402.669553      74.453137     188.636228     169.613593
min         0.000000       0.000000       0.000000       0.000000
25%         0.000000       0.000000       0.000000       0.000000
50%         0.000000       0.000000       0.000000       0.000000
75%        11.000000       1.000000       0.000000       0.000000
max      2964.000000    8488.000000   36851.000000   36875.000000

         Direction_15   Direction_16   Direction_17  Direction_18  \
count   133727.000000  133727.000000  149589.000000  78254.000000
unique            NaN            NaN            NaN           NaN
top               NaN            NaN            NaN           NaN
freq              NaN            NaN            NaN           NaN
mean        11.922387       4.220337       5.282855      0.391149
std        167.864833      48.264907     178.449112      2.007845
min          0.000000       0.000000       0.000000      0.000000
25%          0.000000       0.000000       0.000000      0.000000
50%          0.000000       0.000000       0.000000      0.000000
75%          2.000000       0.000000       0.000000      0.000000
max      36851.000000    8488.000000   36875.000000     35.000000

        Direction_19   Direction_20  Direction_21   Direction_22  \
count   78254.000000   78254.000000  78254.000000   78254.000000
unique           NaN            NaN           NaN            NaN
top              NaN            NaN           NaN            NaN
freq             NaN            NaN           NaN            NaN
mean        1.392542      28.613208      4.995118      19.090756
std       106.256868    1351.391206     14.596867    1350.755822
min         0.000000       0.000000      0.000000       0.000000
25%         0.000000       0.000000      0.000000       0.000000
50%         0.000000       0.000000      0.000000       0.000000
75%         0.000000       2.000000      0.000000       0.000000
max     18162.000000  226103.000000    171.000000  226104.000000

        Direction_23  Direction_24  Direction_25  Direction_26   Direction_27  \
count   31724.000000  15862.000000  15862.000000  15862.000000   15862.000000
unique           NaN           NaN           NaN           NaN            NaN
top              NaN           NaN           NaN           NaN            NaN
freq             NaN           NaN           NaN           NaN            NaN
mean        0.000284     35.000820     28.129114      0.000189      77.628357
std         0.016841    981.315738    981.120222      0.013752    2253.828741
min         0.000000      0.000000      0.000000      0.000000       0.000000
25%         0.000000      0.000000      0.000000      0.000000       0.000000
50%         0.000000      0.000000      0.000000      0.000000       1.000000
75%         0.000000      5.000000      1.000000      0.000000       9.000000
max         1.000000  74363.000000  74364.000000      1.000000  169842.000000

         Direction_28  Total_Traffic
count    15862.000000   1.935960e+05
unique            NaN            NaN
top               NaN            NaN
freq              NaN            NaN
mean        64.244862   1.736705e+02
std       2253.449976   4.791939e+03
min          0.000000   0.000000e+00
25%          0.000000   0.000000e+00
50%          0.000000   0.000000e+00
75%          2.000000   3.000000e+01
max     169842.000000   1.221180e+06

In [5]:
missing = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": round(df.isnull().mean()*100,2)
})

missing.sort_values(
    "Missing Values",
    ascending=False
).head(20)

              Missing Values  Percentage
Direction_9           177822       91.85
Direction_10          177756       91.82
Direction_25          177734       91.81
Direction_27          177734       91.81
Direction_28          177734       91.81
Direction_24          177734       91.81
Direction_26          177734       91.81
Direction_11          161960       83.66
Direction_23          161872       83.61
Direction_8           131490       67.92
Direction_7           131050       67.69
Longitude             128652       66.45
Latitude              128652       66.45
Direction_22          115342       59.58
Direction_20          115342       59.58
Direction_21          115342       59.58
Direction_19          115342       59.58
Direction_18          115342       59.58
Direction_3           114572       59.18
Direction_4            98512       50.89

In [6]:
#remove duplicate rows
print("Before :", len(df))

df = df.drop_duplicates()

print("After :", len(df))

Before : 193596
After : 104522

In [7]:
df.columns = (

    df.columns

    .str.strip()

    .str.replace(" ", "_")

    .str.replace("-", "_")

    .str.replace("/", "_")

    .str.replace("(", "")

    .str.replace(")", "")

    .str.lower()
)

df.columns.tolist()

['week',
 'measurement_site',
 'latitude',
 'longitude',
 'vehicle_category',
 'source_file',
 'time',
 'direction_1',
 'direction_2',
 'direction_3',
 'direction_4',
 'direction_5',
 'direction_6',
 'direction_7',
 'direction_8',
 'direction_9',
 'direction_10',
 'direction_11',
 'direction_12',
 'direction_13',
 'direction_14',
 'direction_15',
 'direction_16',
 'direction_17',
 'direction_18',
 'direction_19',
 'direction_20',
 'direction_21',
 'direction_22',
 'direction_23',
 'direction_24',
 'direction_25',
 'direction_26',
 'direction_27',
 'direction_28',
 'total_traffic']

In [8]:
meta_cols = [

    "week",

    "measurement_site",

    "latitude",

    "longitude",

    "vehicle_category",

    "source_file",

    "time"
]

In [9]:
numeric_cols = [

    c

    for c in df.columns

    if c not in meta_cols
]

In [10]:
for col in numeric_cols:

    df[col] = pd.to_numeric(

        df[col],

        errors="coerce"
    )

In [11]:
df.dtypes

week                    str
measurement_site        str
latitude            float64
longitude           float64
vehicle_category        str
source_file             str
time                    str
direction_1         float64
direction_2         float64
direction_3         float64
direction_4         float64
direction_5         float64
direction_6         float64
direction_7         float64
direction_8         float64
direction_9         float64
direction_10        float64
direction_11        float64
direction_12        float64
direction_13        float64
direction_14        float64
direction_15        float64
direction_16        float64
direction_17        float64
direction_18        float64
direction_19        float64
direction_20        float64
direction_21        float64
direction_22        float64
direction_23        float64
direction_24        float64
direction_25        float64
direction_26        float64
direction_27        float64
direction_28        float64
total_traffic       float64
dtype: object

In [12]:
df["time"] = pd.to_datetime(
    df["time"],
    format="%H:%M:%S",
    errors="coerce"
)

In [13]:
df["hour"] = df["time"].dt.hour

df["minute"] = df["time"].dt.minute

In [14]:
def peak_period(hour):

    if 6 <= hour < 10:
        return "Morning Peak"

    elif 10 <= hour < 15:
        return "Midday"

    elif 15 <= hour < 19:
        return "Evening Peak"

    else:
        return "Off Peak"

In [15]:
df["peak_period"] = df["hour"].apply(peak_period)

In [16]:
traffic_cols = [

    c

    for c in df.columns

    if c.startswith("direction_")
]

In [17]:
df["total_traffic"] = (

    df[traffic_cols]

    .sum(axis=1)
)

In [18]:
df.head()

,week,measurement_site,latitude,longitude,vehicle_category,source_file,time,direction_1,direction_2,direction_3,direction_4,direction_5,direction_6,direction_7,direction_8,direction_9,direction_10,direction_11,direction_12,direction_13,direction_14,direction_15,direction_16,direction_17,direction_18,direction_19,direction_20,direction_21,direction_22,direction_23,direction_24,direction_25,direction_26,direction_27,direction_28,total_traffic,hour,minute,peak_period
0,DZwEI 30.09-07.10,Friedberger Tor,NaN,NaN,Gesamt-Kfz,2024-09-30_to_2024-10-07_UI_202403B0924.xlsx,1900-01-01 00:00:00,5.0,43.0,9.0,17.0,NaN,NaN,74.0,0.0,NaN,NaN,NaN,NaN,NaN,5.0,52.0,0.0,43.0,0.0,0.0,26.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,274.0,0.0,0.0,Off Peak
1,DZwEI 30.09-07.10,Friedberger Tor,NaN,NaN,Gesamt-Kfz,2024-09-30_to_2024-10-07_UI_202403B0924.xlsx,1900-01-01 00:15:00,4.0,31.0,15.0,14.0,NaN,NaN,64.0,0.0,NaN,NaN,NaN,NaN,NaN,4.0,46.0,0.0,31.0,0.0,0.0,29.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,238.0,0.0,15.0,Off Peak
2,DZwEI 30.09-07.10,Friedberger Tor,NaN,NaN,Gesamt-Kfz,2024-09-30_to_2024-10-07_UI_202403B0924.xlsx,1900-01-01 00:30:00,5.0,35.0,7.0,23.0,NaN,NaN,70.0,0.0,NaN,NaN,NaN,NaN,NaN,5.0,42.0,0.0,35.0,0.0,0.0,30.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,252.0,0.0,30.0,Off Peak
3,DZwEI 30.09-07.10,Friedberger Tor,NaN,NaN,Gesamt-Kfz,2024-09-30_to_2024-10-07_UI_202403B0924.xlsx,1900-01-01 00:45:00,4.0,36.0,4.0,15.0,NaN,NaN,59.0,0.0,NaN,NaN,NaN,NaN,NaN,4.0,40.0,0.0,36.0,0.0,0.0,19.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,217.0,0.0,45.0,Off Peak
4,DZwEI 30.09-07.10,Friedberger Tor,NaN,NaN,Gesamt-Kfz,2024-09-30_to_2024-10-07_UI_202403B0924.xlsx,1900-01-01 01:00:00,6.0,15.0,7.0,15.0,NaN,NaN,43.0,0.0,NaN,NaN,NaN,NaN,NaN,6.0,22.0,0.0,15.0,0.0,0.0,22.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,151.0,1.0,0.0,Off Peak

In [19]:
df.isnull().sum().sort_values(
    ascending=False
).head(20)

direction_9     94011
direction_10    93947
direction_24    93925
direction_28    93925
direction_27    93925
direction_26    93925
direction_25    93925
direction_11    86174
direction_23    83326
latitude        70828
longitude       70828
direction_8     69261
direction_7     68929
direction_19    58378
direction_18    58378
direction_21    58378
direction_22    58378
direction_20    58378
direction_3     58180
direction_13    53418
dtype: int64

In [20]:
OUTPUT = PROJECT_DIR / "processed"

OUTPUT.mkdir(exist_ok=True)

df.to_csv(

    OUTPUT / "cleaned_dataset.csv",

    index=False
)

print("Saved Successfully!")

Saved Successfully!

In [21]:
print("="*60)

print("CLEAN DATASET SUMMARY")

print("="*60)

print("Rows :", len(df))

print("Columns :", len(df.columns))

print("Vehicle Categories :", df["vehicle_category"].nunique())

print("Measurement Sites :", df["measurement_site"].nunique())

print("Peak Periods")

print(df["peak_period"].value_counts())

============================================================
CLEAN DATASET SUMMARY
============================================================
Rows : 104522
Columns : 39
Vehicle Categories : 15
Measurement Sites : 11
Peak Periods
peak_period
Off Peak        41909
Midday          25023
Morning Peak    19134
Evening Peak    18456
Name: count, dtype: int64

In [23]:
df["time"] = pd.to_datetime(df["time"])

df["time"] = df["time"].dt.strftime("%H:%M:%S")

In [24]:
traffic_cols = [c for c in df.columns if c.startswith("direction_")]

df[traffic_cols] = df[traffic_cols].fillna(0)

In [25]:
df["total_traffic"] = df[traffic_cols].sum(axis=1)

In [27]:
df.to_csv(
    OUTPUT / "cleaned_dataset.csv",
    index=False
)